.TH "__Cache" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__Cache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__Cache\fP ()"
.br
.ti -1c
.RI "void \fBaddptr\fP (const void *ptr, \fBsize_t\fP v)"
.br
.ti -1c
.RI "bool \fBelligible\fP ()"
.br
.ti -1c
.RI "void * \fBalloc_seg\fP (int segs)"
.br
.ti -1c
.RI "int \fBfree_seg\fP (void *ptr)"
.br
.ti -1c
.RI "int \fBis_exist_ptr\fP (const void *ptr)"
.br
.ti -1c
.RI "int \fBis_rmode64\fP (const void *ptr)"
.br
.ti -1c
.RI "void \fBshow\fP (void)"
.br
.ti -1c
.RI "void \fBfreeptr\fP (const void *ptr)"
.br
.ti -1c
.RI "\fB~__Cache\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__Cache::__Cache ()\fC [inline]\fP"

.SS "__Cache::~__Cache ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void __Cache::addptr (const void * ptr, \fBsize_t\fP v)\fC [inline]\fP"

.SS "void* __Cache::alloc_seg (int segs)\fC [inline]\fP"

.SS "bool __Cache::elligible ()\fC [inline]\fP"

.SS "int __Cache::free_seg (void * ptr)\fC [inline]\fP"

.SS "void __Cache::freeptr (const void * ptr)\fC [inline]\fP"

.SS "int __Cache::is_exist_ptr (const void * ptr)\fC [inline]\fP"

.SS "int __Cache::is_rmode64 (const void * ptr)\fC [inline]\fP"

.SS "void __Cache::show (void)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
