.TH "__Cache" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__Cache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__Cache\fP ()"
.br
.ti -1c
.RI "size_t \fBgetCurrentMem31\fP ()"
.br
.ti -1c
.RI "size_t \fBgetCurrentMem64\fP ()"
.br
.ti -1c
.RI "size_t \fBgetMaxMem31\fP ()"
.br
.ti -1c
.RI "size_t \fBgetMaxMem64\fP ()"
.br
.ti -1c
.RI "void \fBaddptr31\fP (const void *ptr, size_t v)"
.br
.ti -1c
.RI "void * \fBalloc_seg\fP (size_t segs)"
.br
.ti -1c
.RI "int \fBfree_seg\fP (void *ptr, size_t reqsize)"
.br
.ti -1c
.RI "int \fBis_rmode64\fP (const void *ptr)"
.br
.ti -1c
.RI "void \fBfreeptr31\fP (const void *ptr, size_t reqsize)"
.br
.ti -1c
.RI "void \fBdisplayDebris\fP ()"
.br
.ti -1c
.RI "\fB~__Cache\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__Cache::__Cache ()\fC [inline]\fP"

.SS "__Cache::~__Cache ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void __Cache::addptr31 (const void * ptr, size_t v)\fC [inline]\fP"

.SS "void * __Cache::alloc_seg (size_t segs)\fC [inline]\fP"

.SS "void __Cache::displayDebris ()\fC [inline]\fP"

.SS "int __Cache::free_seg (void * ptr, size_t reqsize)\fC [inline]\fP"

.SS "void __Cache::freeptr31 (const void * ptr, size_t reqsize)\fC [inline]\fP"

.SS "size_t __Cache::getCurrentMem31 ()\fC [inline]\fP"

.SS "size_t __Cache::getCurrentMem64 ()\fC [inline]\fP"

.SS "size_t __Cache::getMaxMem31 ()\fC [inline]\fP"

.SS "size_t __Cache::getMaxMem64 ()\fC [inline]\fP"

.SS "int __Cache::is_rmode64 (const void * ptr)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
