.TH "__cpu_relax_workarea" 3 "Tue Jan 18 2022" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__cpu_relax_workarea
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zos\-base\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBsfaddr\fP"
.br
.ti -1c
.RI "unsigned long \fBt0\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* __cpu_relax_workarea::sfaddr"

.SS "unsigned long __cpu_relax_workarea::t0"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
