.TH "__setlibpath" 3 "Wed May 17 2023" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__setlibpath
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zos\-setlibpath\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__setlibpath\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__setlibpath::__setlibpath ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
