.TH "__sem_t" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__sem_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zos\-semaphore\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB____sem_t\fP * \fB_s\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB____sem_t\fP* __sem_t::_s"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
