.TH "__tlsanchor" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__tlsanchor
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pthread_once_t \fBonce\fP"
.br
.ti -1c
.RI "pthread_key_t \fBkey\fP"
.br
.ti -1c
.RI "size_t \fBsz\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "pthread_key_t __tlsanchor::key"

.SS "pthread_once_t __tlsanchor::once"

.SS "size_t __tlsanchor::sz"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
