.TH "_spawn_actions" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_spawn_actions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBOpen_info\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBActionKinds\fP \fBop\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "struct \fB_spawn_actions::Open_info\fP \fBopen_info\fP"
.br
.ti -1c
.RI "int \fBnew_fd\fP"
.br
.ti -1c
.RI "\fB_spawn_actions\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int _spawn_actions::fd"

.SS "int _spawn_actions::new_fd"

.SS "\fB_spawn_actions\fP* _spawn_actions::next"

.SS "\fBActionKinds\fP _spawn_actions::op"

.SS "struct \fB_spawn_actions::Open_info\fP _spawn_actions::open_info"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
