.TH "_spawn_actions::Open_info" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_spawn_actions::Open_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBpath\fP"
.br
.ti -1c
.RI "int \fBoflags\fP"
.br
.ti -1c
.RI "\fBmode_t\fP \fBmode\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmode_t\fP _spawn_actions::Open_info::mode"

.SS "int _spawn_actions::Open_info::oflags"

.SS "const char* _spawn_actions::Open_info::path"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
