.TH "src/clib-overrides.cc" 3 "Wed May 17 2023" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/clib-overrides.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'zos\-base\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_AE_BIMODAL\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _AE_BIMODAL   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
