.TH "CSRSI_PSA" 3 "Tue Jan 18 2022" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSRSI_PSA
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBCSRSI_psa_filler\fP [16]"
.br
.ti -1c
.RI "struct \fBCSRSI_CVT\fP * \fBCSRSI_cvt\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBCSRSI_CVT\fP* CSRSI_PSA::CSRSI_cvt"

.SS "char CSRSI_PSA::CSRSI_psa_filler[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
