.TH "CSRSI_CSRT" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSRSI_CSRT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBCSRSI_csrt_filler1\fP [48]"
.br
.ti -1c
.RI "\fBCSRSI_calltype\fP * \fBCSRSI_addr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBCSRSI_calltype\fP* CSRSI_CSRT::CSRSI_addr"

.SS "unsigned char CSRSI_CSRT::CSRSI_csrt_filler1[48]"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
