.TH "include/edcwccwi.h" 3 "Wed May 17 2023" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/edcwccwi.h
.SH SYNOPSIS
.br
.PP
\fC#include <features\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__EDC_LE\fP   0x10000000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __EDC_LE   0x10000000"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
