.TH "espiearg" 3 "Thu Jun 10 2021" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
espiearg
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void *__ptr32 \fBexitproc\fP"
.br
.ti -1c
.RI "void *__ptr32 \fBexitargs\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "void *__ptr32 \fBreserved\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* __ptr32 espiearg::exitargs"

.SS "void* __ptr32 espiearg::exitproc"

.SS "int espiearg::flags"

.SS "void* __ptr32 espiearg::reserved"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
