.TH "fdAttributeCache" 3 "Thu Jun 10 2021" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fdAttributeCache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfd_attribute\fP \fBget_attribute\fP (int fd)"
.br
.ti -1c
.RI "void \fBset_attribute\fP (int fd, \fBfd_attribute\fP attr)"
.br
.ti -1c
.RI "void \fBunset_attribute\fP (int fd)"
.br
.ti -1c
.RI "void \fBclear\fP (void)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void fdAttributeCache::clear (void)\fC [inline]\fP"

.SS "\fBfd_attribute\fP fdAttributeCache::get_attribute (int fd)\fC [inline]\fP"

.SS "void fdAttributeCache::set_attribute (int fd, \fBfd_attribute\fP attr)\fC [inline]\fP"

.SS "void fdAttributeCache::unset_attribute (int fd)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
