.TH "IFAARGS" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAARGS
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBprefix\fP"
.br
.ti -1c
.RI "char \fBid\fP [8]"
.br
.ti -1c
.RI "short \fBlistlen\fP"
.br
.ti -1c
.RI "char \fBversion\fP"
.br
.ti -1c
.RI "char \fBrequest\fP"
.br
.ti -1c
.RI "char \fBprodowner\fP [16]"
.br
.ti -1c
.RI "char \fBprodname\fP [16]"
.br
.ti -1c
.RI "char \fBprodvers\fP [8]"
.br
.ti -1c
.RI "char \fBprodqual\fP [8]"
.br
.ti -1c
.RI "char \fBprodid\fP [8]"
.br
.ti -1c
.RI "char \fBdomain\fP"
.br
.ti -1c
.RI "char \fBscope\fP"
.br
.ti -1c
.RI "char \fBrsv0001\fP"
.br
.ti -1c
.RI "char \fBflags\fP"
.br
.ti -1c
.RI "char *__ptr32 \fBprtoken_addr\fP"
.br
.ti -1c
.RI "char *__ptr32 \fBbegtime_addr\fP"
.br
.ti -1c
.RI "char *__ptr32 \fBdata_addr\fP"
.br
.ti -1c
.RI "char \fBxformat\fP"
.br
.ti -1c
.RI "char \fBrsv0002\fP [3]"
.br
.ti -1c
.RI "char *__ptr32 \fBcurrentdata_addr\fP"
.br
.ti -1c
.RI "char *__ptr32 \fBenddata_addr\fP"
.br
.ti -1c
.RI "char *__ptr32 \fBendtime_addr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* __ptr32 IFAARGS::begtime_addr"

.SS "char* __ptr32 IFAARGS::currentdata_addr"

.SS "char* __ptr32 IFAARGS::data_addr"

.SS "char IFAARGS::domain"

.SS "char* __ptr32 IFAARGS::enddata_addr"

.SS "char* __ptr32 IFAARGS::endtime_addr"

.SS "char IFAARGS::flags"

.SS "char IFAARGS::id[8]"

.SS "short IFAARGS::listlen"

.SS "int IFAARGS::prefix"

.SS "char IFAARGS::prodid[8]"

.SS "char IFAARGS::prodname[16]"

.SS "char IFAARGS::prodowner[16]"

.SS "char IFAARGS::prodqual[8]"

.SS "char IFAARGS::prodvers[8]"

.SS "char* __ptr32 IFAARGS::prtoken_addr"

.SS "char IFAARGS::request"

.SS "char IFAARGS::rsv0001"

.SS "char IFAARGS::rsv0002[3]"

.SS "char IFAARGS::scope"

.SS "char IFAARGS::version"

.SS "char IFAARGS::xformat"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
