.TH "IFAEDSTA_parms" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFAEDSTA_parms
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void *__ptr32 \fBargs\fP [8]"
.br
.ti -1c
.RI "char \fBcpo\fP [16]"
.br
.ti -1c
.RI "char \fBcpnpp\fP [16]"
.br
.ti -1c
.RI "char \fBcfnpp\fP [16]"
.br
.ti -1c
.RI "char \fBcpidpp\fP [16]"
.br
.ti -1c
.RI "int \fBcoinfo\fP [4]"
.br
.ti -1c
.RI "int \fBcflpp\fP"
.br
.ti -1c
.RI "int \fBcfspp\fP [256]"
.br
.ti -1c
.RI "int \fBcrcpp\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* __ptr32 IFAEDSTA_parms::args[8]"

.SS "int IFAEDSTA_parms::cflpp"

.SS "char IFAEDSTA_parms::cfnpp[16]"

.SS "int IFAEDSTA_parms::cfspp[256]"

.SS "int IFAEDSTA_parms::coinfo[4]"

.SS "char IFAEDSTA_parms::cpidpp[16]"

.SS "char IFAEDSTA_parms::cpnpp[16]"

.SS "char IFAEDSTA_parms::cpo[16]"

.SS "int IFAEDSTA_parms::crcpp"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
