.TH "IntHash" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntHash
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const int &n) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "size_t IntHash::operator() (const int & n) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
