.TH "include/limits.h" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/limits.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPATH_MAX\fP   _XOPEN_PATH_MAX"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PATH_MAX   _XOPEN_PATH_MAX"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
