.TH "posix_spawnattr_t" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
posix_spawnattr_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spawn\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sigset_t * \fBmask\fP"
.br
.ti -1c
.RI "short \fBflags\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "short posix_spawnattr_t::flags"

.SS "sigset_t* posix_spawnattr_t::mask"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
