.TH "sem_t" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sem_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zos\-semaphore\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.ti -1c
.RI "unsigned int \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "pthread_cond_t sem_t::cond"

.SS "pthread_mutex_t sem_t::mutex"

.SS "unsigned int sem_t::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
