.TH "Semaphore" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Semaphore
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zos\-base\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB____sem_t\fP * \fB_s\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB____sem_t\fP* Semaphore::_s"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
