.TH "si00" 3 "Wed May 17 2023" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
si00
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBsi00cpcvariety\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fB_si00validsi11v1\fP: 1"
.br
.ti -1c
.RI "   int \fB_si00validsi22v1\fP: 1"
.br
.ti -1c
.RI "   int \fB_si00validsi22v2\fP: 1"
.br
.ti -1c
.RI "   int \fB_si00validsi22v3\fP: 1"
.br
.ti -1c
.RI "   int \fB_filler1\fP: 4"
.br
.ti -1c
.RI "} \fBsi00validityflags\fP"
.br
.ti -1c
.RI "unsigned char \fB_filler2\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBsi00pccacpid\fP [12]"
.br
.ti -1c
.RI "unsigned char \fBsi00pccacpua\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBsi00pccacafm\fP [2]"
.br
.ti -1c
.RI "unsigned char \fB_filler3\fP [4]"
.br
.ti -1c
.RI "unsigned char \fBsi00lastupdatetimestamp\fP [8]"
.br
.ti -1c
.RI "unsigned char \fBsi00pcca_cpu_address_mask\fP [8]"
.br
.ti -1c
.RI "unsigned char \fB_filler4\fP [24]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int si00::_filler1"

.SS "unsigned char si00::_filler2[2]"

.SS "unsigned char si00::_filler3[4]"

.SS "unsigned char si00::_filler4[24]"

.SS "int si00::_si00validsi11v1"

.SS "int si00::_si00validsi22v1"

.SS "int si00::_si00validsi22v2"

.SS "int si00::_si00validsi22v3"

.SS "char si00::si00cpcvariety"

.SS "unsigned char si00::si00lastupdatetimestamp[8]"

.SS "unsigned char si00::si00pcca_cpu_address_mask[8]"

.SS "unsigned char si00::si00pccacafm[2]"

.SS "unsigned char si00::si00pccacpid[12]"

.SS "unsigned char si00::si00pccacpua[2]"

.SS "struct { \&.\&.\&. }  si00::si00validityflags"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
