.TH "si11v1" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
si11v1
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fB_filler1\fP [32]"
.br
.ti -1c
.RI "unsigned char \fBsi11v1cpcmanufacturer\fP [16]"
.br
.ti -1c
.RI "unsigned char \fBsi11v1cpctype\fP [4]"
.br
.ti -1c
.RI "unsigned char \fB_filler2\fP [12]"
.br
.ti -1c
.RI "unsigned char \fBsi11v1cpcmodelcapident\fP [16]"
.br
.ti -1c
.RI "unsigned char \fBsi11v1cpcsequencecode\fP [16]"
.br
.ti -1c
.RI "unsigned char \fBsi11v1cpcplantofmanufacture\fP [4]"
.br
.ti -1c
.RI "unsigned char \fBsi11v1cpcmodel1\fP [16]"
.br
.ti -1c
.RI "unsigned char \fB_filler3\fP [3980]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char si11v1::_filler1[32]"

.SS "unsigned char si11v1::_filler2[12]"

.SS "unsigned char si11v1::_filler3[3980]"

.SS "unsigned char si11v1::si11v1cpcmanufacturer[16]"

.SS "unsigned char si11v1::si11v1cpcmodel1[16]"

.SS "unsigned char si11v1::si11v1cpcmodelcapident[16]"

.SS "unsigned char si11v1::si11v1cpcplantofmanufacture[4]"

.SS "unsigned char si11v1::si11v1cpcsequencecode[16]"

.SS "unsigned char si11v1::si11v1cpctype[4]"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
