.TH "si22v1alt" 3 "Thu Jun 10 2021" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
si22v1alt
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBsi22v1altcpucapability\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned char \fB_si22v1altmpcpucapaf\fP [2]"
.br
.ti -1c
.RI "   unsigned char \fB_filler2\fP [4050]"
.br
.ti -1c
.RI "} \fBsi22v1altmpcpucapafs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char si22v1alt::_filler2[4050]"

.SS "unsigned char si22v1alt::_si22v1altmpcpucapaf[2]"

.SS "unsigned int si22v1alt::si22v1altcpucapability"

.SS "struct { \&.\&.\&. }  si22v1alt::si22v1altmpcpucapafs"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
