.TH "si22v3db" 3 "Thu Jun 10 2021" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
si22v3db
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fB_filler1\fP [4]"
.br
.ti -1c
.RI "unsigned int \fBsi22v3dbtotallcpucount\fP: 16"
.br
.ti -1c
.RI "unsigned int \fBsi22v3dbconfiguredlcpucount\fP: 16"
.br
.ti -1c
.RI "unsigned int \fBsi22v3dbstandbylcpucount\fP: 16"
.br
.ti -1c
.RI "unsigned int \fBsi22v3dbreservedlcpucount\fP: 16"
.br
.ti -1c
.RI "unsigned char \fBsi22v3dbcpcname\fP [8]"
.br
.ti -1c
.RI "unsigned char \fBsi22v3dbcpccaf\fP [4]"
.br
.ti -1c
.RI "unsigned char \fBsi22v3dbvmhpidentifier\fP [16]"
.br
.ti -1c
.RI "unsigned char \fB_filler2\fP [24]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char si22v3db::_filler1[4]"

.SS "unsigned char si22v3db::_filler2[24]"

.SS "unsigned int si22v3db::si22v3dbconfiguredlcpucount"

.SS "unsigned char si22v3db::si22v3dbcpccaf[4]"

.SS "unsigned char si22v3db::si22v3dbcpcname[8]"

.SS "unsigned int si22v3db::si22v3dbreservedlcpucount"

.SS "unsigned int si22v3db::si22v3dbstandbylcpucount"

.SS "unsigned int si22v3db::si22v3dbtotallcpucount"

.SS "unsigned char si22v3db::si22v3dbvmhpidentifier[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
