.TH "si22v3" 3 "Tue Jan 18 2022" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
si22v3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fB_filler1\fP [28]"
.br
.ti -1c
.RI "unsigned char \fB_filler2\fP [3]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned int \fB_filler3\fP: 4"
.br
.ti -1c
.RI "   unsigned int \fB_si22v3dbcount\fP: 4"
.br
.ti -1c
.RI "} \fBsi22v3dbcountfield\fP"
.br
.ti -1c
.RI "\fBsi22v3db\fP \fBsi22v3dbe\fP [8]"
.br
.ti -1c
.RI "unsigned char \fB_filler5\fP [3552]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char si22v3::_filler1[28]"

.SS "unsigned char si22v3::_filler2[3]"

.SS "unsigned int si22v3::_filler3"

.SS "unsigned char si22v3::_filler5[3552]"

.SS "unsigned int si22v3::_si22v3dbcount"

.SS "struct { \&.\&.\&. }  si22v3::si22v3dbcountfield"

.SS "\fBsi22v3db\fP si22v3::si22v3dbe[8]"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
