.TH "include/signal.h" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/signal.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNSIG\fP   42"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NSIG   42"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
