.TH "siv1" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
siv1
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsi00\fP \fBsiv1si00\fP"
.br
.ti -1c
.RI "\fBsi11v1\fP \fBsiv1si11v1\fP"
.br
.ti -1c
.RI "\fBsi22v1\fP \fBsiv1si22v1\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsi00\fP siv1::siv1si00"

.SS "\fBsi11v1\fP siv1::siv1si11v1"

.SS "\fBsi22v1\fP siv1::siv1si22v1"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
