.TH "siv1v2v3" 3 "Wed May 17 2023" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
siv1v2v3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsi00\fP \fBsiv1v2v3si00\fP"
.br
.ti -1c
.RI "\fBsi11v1\fP \fBsiv1v2v3si11v1\fP"
.br
.ti -1c
.RI "\fBsi22v1\fP \fBsiv1v2v3si22v1\fP"
.br
.ti -1c
.RI "\fBsi22v2\fP \fBsiv1v2v3si22v2\fP"
.br
.ti -1c
.RI "\fBsi22v3\fP \fBsiv1v2v3si22v3\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsi00\fP siv1v2v3::siv1v2v3si00"

.SS "\fBsi11v1\fP siv1v2v3::siv1v2v3si11v1"

.SS "\fBsi22v1\fP siv1v2v3::siv1v2v3si22v1"

.SS "\fBsi22v2\fP siv1v2v3::siv1v2v3si22v2"

.SS "\fBsi22v3\fP siv1v2v3::siv1v2v3si22v3"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
