.TH "siv1v2" 3 "Thu Jun 10 2021" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
siv1v2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsi00\fP \fBsiv1v2si00\fP"
.br
.ti -1c
.RI "\fBsi11v1\fP \fBsiv1v2si11v1\fP"
.br
.ti -1c
.RI "\fBsi22v1\fP \fBsiv1v2si22v1\fP"
.br
.ti -1c
.RI "\fBsi22v2\fP \fBsiv1v2si22v2\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsi00\fP siv1v2::siv1v2si00"

.SS "\fBsi11v1\fP siv1v2::siv1v2si11v1"

.SS "\fBsi22v1\fP siv1v2::siv1v2si22v1"

.SS "\fBsi22v2\fP siv1v2::siv1v2si22v2"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
