.TH "siv2v3" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
siv2v3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsi00\fP \fBsiv2v3si00\fP"
.br
.ti -1c
.RI "\fBsi22v2\fP \fBsiv2v3si22v2\fP"
.br
.ti -1c
.RI "\fBsi22v3\fP \fBsiv2v3si22v3\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsi00\fP siv2v3::siv2v3si00"

.SS "\fBsi22v2\fP siv2v3::siv2v3si22v2"

.SS "\fBsi22v3\fP siv2v3::siv2v3si22v3"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
