.TH "siv3" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
siv3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <csrsic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsi00\fP \fBsiv3si00\fP"
.br
.ti -1c
.RI "\fBsi22v3\fP \fBsiv3si22v3\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsi00\fP siv3::siv3si00"

.SS "\fBsi22v3\fP siv3::siv3si22v3"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
