.TH "include/string.h" 3 "Wed May 17 2023" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/string.h
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__strdup_orig\fP   strdup"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __strdup_orig   strdup"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
