.TH "thunk24" 3 "Thu Jun 10 2021" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thunk24
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fB_force_address_align\fP"
.br
.ti -1c
.RI "unsigned short \fBsam24\fP"
.br
.ti -1c
.RI "unsigned short \fBbasr\fP"
.br
.ti -1c
.RI "unsigned short \fBsam64\fP"
.br
.ti -1c
.RI "unsigned short \fBloadr14\fP [3]"
.br
.ti -1c
.RI "unsigned short \fBbr14\fP"
.br
.ti -1c
.RI "void * \fBbraddr\fP"
.br
.ti -1c
.RI "unsigned int \fBdsa\fP [18]"
.br
.ti -1c
.RI "unsigned int \fBupperhalf\fP [15]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned short thunk24::_force_address_align"

.SS "unsigned short thunk24::basr"

.SS "unsigned short thunk24::br14"

.SS "void* thunk24::braddr"

.SS "unsigned int thunk24::dsa[18]"

.SS "unsigned short thunk24::loadr14[3]"

.SS "unsigned short thunk24::sam24"

.SS "unsigned short thunk24::sam64"

.SS "unsigned int thunk24::upperhalf[15]"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
