.TH "timer_parm" 3 "Wed Nov 11 2020" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timer_parm
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsecs\fP"
.br
.ti -1c
.RI "pthread_t \fBtid\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int timer_parm::secs"

.SS "pthread_t timer_parm::tid"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
