.TH "include/sys/types.h" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/sys/types.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned long long \fBfsid_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned long long \fBfsid_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
