.TH "src/zos-tls.cc" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/zos-tls.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'zos\-tls\&.h'\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__tlsanchor\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_POSIX_SOURCE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB__tlsanchor\fP * \fB__tlsvaranchor_create\fP (size_t sz)"
.br
.ti -1c
.RI "void \fB__tlsvaranchor_destroy\fP (struct \fB__tlsanchor\fP *anchor)"
.br
.ti -1c
.RI "void * \fB__tlsPtrFromAnchor\fP (struct \fB__tlsanchor\fP *anchor, const void *initvalue)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _POSIX_SOURCE"

.SH "Function Documentation"
.PP 
.SS "void * __tlsPtrFromAnchor (struct \fB__tlsanchor\fP * anchor, const void * initvalue)"

.SS "struct \fB__tlsanchor\fP * __tlsvaranchor_create (size_t sz)"

.SS "void __tlsvaranchor_destroy (struct \fB__tlsanchor\fP * anchor)"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
