.TH "src/zos-spawn.cc" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/zos-spawn.cc
.SH SYNOPSIS
.br
.PP
\fC#include <spawn\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_spawn_actions\fP"
.br
.ti -1c
.RI "struct \fB_spawn_actions::Open_info\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_POSIX_SOURCE\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBActionKinds\fP { \fBop_open\fP, \fBop_close\fP, \fBop_dup2\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBposix_spawn_file_actions_init\fP (\fBposix_spawn_file_actions_t\fP *act)"
.br
.ti -1c
.RI "void \fBprintActions\fP (const \fBposix_spawn_file_actions_t\fP *act)"
.br
.ti -1c
.RI "int \fBposix_spawn_file_actions_addclose\fP (\fBposix_spawn_file_actions_t\fP *act, int pipe_fd)"
.br
.ti -1c
.RI "int \fBposix_spawn_file_actions_addopen\fP (\fBposix_spawn_file_actions_t\fP *act, int pipe_fd, const char *path, int flags, \fBmode_t\fP mode)"
.br
.ti -1c
.RI "int \fBposix_spawn_file_actions_adddup2\fP (\fBposix_spawn_file_actions_t\fP *act, int pipe_fd, int nfd)"
.br
.ti -1c
.RI "int \fBposix_spawn_file_actions_destroy\fP (\fBposix_spawn_file_actions_t\fP *act)"
.br
.ti -1c
.RI "int \fBposix_spawnattr_init\fP (\fBposix_spawnattr_t\fP *attr)"
.br
.ti -1c
.RI "int \fBposix_spawnattr_setsigmask\fP (\fBposix_spawnattr_t\fP *attr, sigset_t *mask)"
.br
.ti -1c
.RI "int \fBposix_spawnattr_setflags\fP (\fBposix_spawnattr_t\fP *attr, short flags)"
.br
.ti -1c
.RI "int \fBposix_spawnattr_destroy\fP (\fBposix_spawnattr_t\fP *attr)"
.br
.ti -1c
.RI "int \fBposix_spawn\fP (pid_t *pid, const char *cmd, const \fBposix_spawn_file_actions_t\fP *act, const \fBposix_spawnattr_t\fP *attr, char *const args[], char *const env[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _POSIX_SOURCE"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBActionKinds\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIop_open \fP\fP
.TP
\fB\fIop_close \fP\fP
.TP
\fB\fIop_dup2 \fP\fP
.SH "Function Documentation"
.PP 
.SS "int posix_spawn (pid_t * pid, const char * cmd, const \fBposix_spawn_file_actions_t\fP * act, const \fBposix_spawnattr_t\fP * attr, char *const args[], char *const env[])"

.SS "int posix_spawn_file_actions_addclose (\fBposix_spawn_file_actions_t\fP * act, int pipe_fd)"

.SS "int posix_spawn_file_actions_adddup2 (\fBposix_spawn_file_actions_t\fP * act, int pipe_fd, int nfd)"

.SS "int posix_spawn_file_actions_addopen (\fBposix_spawn_file_actions_t\fP * act, int pipe_fd, const char * path, int flags, \fBmode_t\fP mode)"

.SS "int posix_spawn_file_actions_destroy (\fBposix_spawn_file_actions_t\fP * act)"

.SS "int posix_spawn_file_actions_init (\fBposix_spawn_file_actions_t\fP * act)"

.SS "int posix_spawnattr_destroy (\fBposix_spawnattr_t\fP * attr)"

.SS "int posix_spawnattr_init (\fBposix_spawnattr_t\fP * attr)"

.SS "int posix_spawnattr_setflags (\fBposix_spawnattr_t\fP * attr, short flags)"

.SS "int posix_spawnattr_setsigmask (\fBposix_spawnattr_t\fP * attr, sigset_t * mask)"

.SS "void printActions (const \fBposix_spawn_file_actions_t\fP * act)"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
