.TH "include/zos-sys-info.h" 3 "Tue Jan 18 2022" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/zos-sys-info.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBZOSCCT\fP"
.br
.ti -1c
.RI "struct \fBZOSRMCT\fP"
.br
.ti -1c
.RI "struct \fBZOSRCE\fP"
.br
.ti -1c
.RI "struct \fBZOSCVT\fP"
.br
.ti -1c
.RI "struct \fBZOSPSA\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBZOSCCT\fP \fBZOSCCT_t\fP"
.br
.ti -1c
.RI "typedef struct \fBZOSRMCT\fP \fBZOSRMCT_t\fP"
.br
.ti -1c
.RI "typedef struct \fBZOSRCE\fP \fBZOSRCE_t\fP"
.br
.ti -1c
.RI "typedef struct \fBZOSCVT\fP \fBZOSCVT_t\fP"
.br
.ti -1c
.RI "typedef struct \fBZOSPSA\fP \fBZOSPSA_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBZOSCCT\fP \fBZOSCCT_t\fP"

.SS "typedef struct \fBZOSCVT\fP \fBZOSCVT_t\fP"

.SS "typedef struct \fBZOSPSA\fP \fBZOSPSA_t\fP"

.SS "typedef struct \fBZOSRCE\fP \fBZOSRCE_t\fP"

.SS "typedef struct \fBZOSRMCT\fP \fBZOSRMCT_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
