.TH "include/zos-macros.h" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/zos-macros.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__Z_EXPORT\fP   __attribute__((visibility('default')))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __Z_EXPORT   __attribute__((visibility('default')))"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
