.TH "src/zos-semaphore.cc" 3 "Wed May 17 2023" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/zos-semaphore.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'zos\-semaphore\&.h'\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/modes\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fB__zsync_val_compare_and_swap32\fP (volatile unsigned int *__p, unsigned int __compVal, unsigned int __exchVal)"
.br
.ti -1c
.RI "unsigned int \fBatomic_dec\fP (volatile unsigned int *loc)"
.br
.ti -1c
.RI "unsigned int \fBatomic_inc\fP (volatile unsigned int *loc)"
.br
.ti -1c
.RI "int \fB__sem_init\fP (\fB__sem_t\fP *s0, int shared, unsigned int val)"
.br
.ti -1c
.RI "int \fB__sem_post\fP (\fB__sem_t\fP *s0)"
.br
.ti -1c
.RI "int \fB__sem_trywait\fP (\fB__sem_t\fP *s0)"
.br
.ti -1c
.RI "int \fB__sem_timedwait\fP (\fB__sem_t\fP *s0, const struct timespec *abs_timeout)"
.br
.ti -1c
.RI "int \fB__sem_wait\fP (\fB__sem_t\fP *s0)"
.br
.ti -1c
.RI "int \fB__sem_destroy\fP (\fB__sem_t\fP *s0)"
.br
.ti -1c
.RI "int \fB__sem_getvalue\fP (\fB__sem_t\fP *s0, int *sval)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int __sem_destroy (\fB__sem_t\fP * s0)"

.SS "int __sem_getvalue (\fB__sem_t\fP * s0, int * sval)"

.SS "int __sem_init (\fB__sem_t\fP * s0, int shared, unsigned int val)"
TODO(itodorov) - zos: document these interfaces 
.SS "int __sem_post (\fB__sem_t\fP * s0)"

.SS "int __sem_timedwait (\fB__sem_t\fP * s0, const struct timespec * abs_timeout)"

.SS "int __sem_trywait (\fB__sem_t\fP * s0)"

.SS "int __sem_wait (\fB__sem_t\fP * s0)"

.SS "unsigned int __zsync_val_compare_and_swap32 (volatile unsigned int * __p, unsigned int __compVal, unsigned int __exchVal)"

.SS "unsigned int atomic_dec (volatile unsigned int * loc)"

.SS "unsigned int atomic_inc (volatile unsigned int * loc)"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
