.TH "include/zos-setlibpath.h" 3 "Wed May 17 2023" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/zos-setlibpath.h
.SH SYNOPSIS
.br
.PP
\fC#include 'zos\-macros\&.h'\fP
.br
\fC#include <libgen\&.h>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <sys/ps\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__setlibpath\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
