.TH "include/zos.h" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/zos.h
.SH SYNOPSIS
.br
.PP
\fC#include 'csrsic\&.h'\fP
.br
\fC#include 'edcwccwi\&.h'\fP
.br
\fC#include 'zos\-base\&.h'\fP
.br
\fC#include 'zos\-semaphore\&.h'\fP
.br
\fC#include 'zos\-sys\-info\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAJOR_VERSION\fP   3"
.br
.ti -1c
.RI "#define \fBMINOR_VERSION\fP   1"
.br
.ti -1c
.RI "#define \fBPATCH_VERSION\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAJOR_VERSION   3"

.SS "#define MINOR_VERSION   1"

.SS "#define PATCH_VERSION   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
