.TH "ZOSCVT" 3 "Tue Jan 18 2022" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZOSCVT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zos\-sys\-info\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBfiller\fP [604]"
.br
.ti -1c
.RI "struct \fBZOSRMCT\fP *__ptr32 \fBrmct\fP"
.br
.ti -1c
.RI "uint8_t \fBfiller1\fP [560]"
.br
.ti -1c
.RI "struct \fBZOSRCE\fP *__ptr32 \fBrce\fP"
.br
.ti -1c
.RI "uint8_t \fBfiller2\fP [92]"
.br
.ti -1c
.RI "uint8_t \fBcvtoslvl\fP [16]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t ZOSCVT::cvtoslvl[16]"

.SS "uint8_t ZOSCVT::filler[604]"

.SS "uint8_t ZOSCVT::filler1[560]"

.SS "uint8_t ZOSCVT::filler2[92]"

.SS "struct \fBZOSRCE\fP* __ptr32 ZOSCVT::rce"

.SS "struct \fBZOSRMCT\fP* __ptr32 ZOSCVT::rmct"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
