.TH "src/zoslib-help.cc" 3 "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/zoslib-help.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'zos\-base\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
