.TH "ZOSPCCAVT" 3 "Wed May 17 2023" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZOSPCCAVT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zos\-sys\-info\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBZOSPCCA\fP *__ptr32 \fBcpu0\fP"
.br
.ti -1c
.RI "char \fBfiller1\fP [252]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBZOSPCCA\fP* __ptr32 ZOSPCCAVT::cpu0"

.SS "char ZOSPCCAVT::filler1[252]"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
