.TH "ZOSPSA" 3 "Tue Jan 18 2022" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZOSPSA
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zos\-sys\-info\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBfiller\fP [16]"
.br
.ti -1c
.RI "struct \fBZOSCVT\fP *__ptr32 \fBcvt\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBZOSCVT\fP* __ptr32 ZOSPSA::cvt"

.SS "uint8_t ZOSPSA::filler[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
