.TH "ZOSRCE" 3 "Tue Jan 18 2022" "zoslib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZOSRCE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zos\-sys\-info\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBid\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBpool\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t ZOSRCE::id[4]"

.SS "uint32_t ZOSRCE::pool"


.SH "Author"
.PP 
Generated automatically by Doxygen for zoslib from the source code\&.
